[project]
name = "deep-research-starter"
version = "0.1.0"
description = "Starter code for using the OpenAI Deep Research API, brought to you by Harvey"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai==1.93.0",
    "streamlit==1.46.0",
]
